### ISSUE TITLE
Support for PGN variations

### ISSUE THREAD

**Issue by siansell** [siansell/pgnviewer#3]
Working on it, use one Chess() object for each variation with the start position set to the place in the game where the variation starts.

**Comment by italianplayer** [comment]
hello, I am trying to use your code. I downloaded https://github.com/siansell/pgnviewer/archive/master.zip and would like to know how to load a pgn. Can you tell me an example of page loading pgn?
thank 1000 (sorry for my english)

**Comment by crapomat** [comment]
You cant load a file in this pgnviewer. You need to modify (or create new from template) js/pgnviewer.js. You just open your .pgn with a texteditor, select all, copy it and insert it into pgnData array, you must add ' at beginning of lines and ', at end of lines (exerpt last line, it only needs ' at end). Also add a comma after last closing bracket of pgnData array. etc. It's very simple to do, you can use PHP or something to create files.
